# -*- coding: utf-8 -*-
"""Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4wAMWHX8LRq9XYb262yvfX4G_Mk9CPZ

Import Libraries
"""

!pip install scikit-learn-extra

#Data manipulation
import numpy as np
import pandas as pd

#Data presentation/visualisation
import matplotlib.pyplot as plt
import seaborn as sns

#File Import
from google.colab import files
import io

#Data Preprocessing
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.pipeline import Pipeline

from statsmodels.stats.proportion import proportions_ztest

#Data Split
from sklearn.model_selection import train_test_split, StratifiedKFold

#Decision Trees
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text

#Model Stats
from scipy import stats
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score
)

from sklearn.model_selection import cross_val_score
from imblearn.metrics import geometric_mean_score

#Unsupervised learning
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score

from scipy.cluster.hierarchy import dendrogram, linkage

# K-medoids is not included in standard scikit-learn.
from sklearn_extra.cluster import KMedoids

print("Libraries loaded.")

"""# Task 1
**Data preprocessing and exploratory analysis**

Read Dataset
Link: https://www.kaggle.com/datasets/zeyadmohamed26/netflix-customer-churn-and-engagement-analytics?resource=download&select=netflix_customer_churn.csv

# Attributes for netflix_customer_churn.csv dataset:
1 customer_id - unique anonymous subscriber identifier (string: UUID format)

2 age - customer age in completed years (numeric: from 18 to 70)

3 gender - customer demographic self-identification (nominal: 'Female', 'Male', or 'Other')

4 subscription_type - current Netflix subscription tier (nominal: 'Basic', 'Standard', or 'Premium')

5 watch_hours - total cumulative monthly streaming hours (numeric: from 0.10 to 110.40)

6 last_login_days - number of days elapsed since the subscriber last logged in (numeric: from 0 to 60)

7 region - primary geographic operational market (nominal: 'Africa', 'Asia', 'Europe', 'North America', 'Oceania', or 'South America')

8 device - primary viewing hardware platform (nominal: 'Desktop', 'Laptop', 'Mobile', 'TV', or 'Tablet')

9 monthly_fee - regular monthly recurring fee billed to account in USD (numeric: 8.99, 13.99, or 17.99)

10 churned - whether subscriber cancelled service (binary: 0 - active or 1 - churned, output target)

11 payment_method - payment method registered on the billing profile (nominal: 'Credit Card', 'Crypto', 'Debit Card', 'Gift Card', or 'PayPal')

12 number_of_profiles - active viewer sub-profiles on account (numeric: from 1 to 5)

13 avg_watch_time_per_day - calculated daily streaming engagement average in hours (numeric: from 0.01 to 4.97)

14 favorite_genre - most frequently streamed content genre (nominal: 'Action', 'Comedy', 'Drama', 'Horror', 'Romance', 'Sci-Fi', or 'Thriller')

---------------------------------------------------------------

#***TO RUN THE CODE: DATASET (.csv) SHOULD BE UPLOADED TO COLAB***

Read the dataset
"""

uploaded = files.upload()

df = pd.read_csv("netflix_customer_churn.csv")

# Display the first five observations
display(df.head())

# Dataset dimensions
print(f"Dataset shape: {df.shape}")
print("Number of observations:", df.shape[0])
print("Number of variables:", df.shape[1])

# Variable names and data types
print("--------------------------")
print("\nVariable information:")
df.info()

"""Drop *IDs* and *avg_watch_time_per_day* and *monthly_fee* as a redundant"""

df =df.drop(columns=['customer_id'])
df =df.drop(columns=['avg_watch_time_per_day'])
df =df.drop(columns=['monthly_fee'])
display(df.head())
# Dataset dimensions
print(f"Dataset shape: {df.shape}")
print("Number of observations:", df.shape[0])
print("Number of variables:", df.shape[1])

"""
Check for Missing Values"""

missing_values_null = pd.DataFrame({
    "Missing values": df.isnull().sum(),
    "Missing percentage (%)": df.isnull().mean() * 100
})

missing_values_nan = pd.DataFrame({
    "Missing values": df.isna().sum(),
    "Missing percentage (%)": df.isna().mean() * 100
})

print("NULL VALUES:")
display(missing_values_null)

print("\n\nNAN VALUES:")
display(missing_values_nan)

"""Delete Rows with Missing Values"""

#print("\nDrop columns with at least 1 NaN:\n", df.dropna(axis=1))
#print("\nDrop rows where all values are NaN:\n", df.dropna(how='all'))
print("\nDrop rows with at least 1 NaN/NULL:\n", df.dropna())

"""Check for Written Errors in Dataset"""

for col in df.columns:
    print(df[col].value_counts())
    print("-"*30)

"""Check for Duplicates

"""

print(df.duplicated(keep='last'))
print("\nTotal number of duplicates:",df.duplicated().sum())

"""Delete Duplicates"""

initial_len = len(df)
print("\nInitial length:",initial_len)
df = df.drop_duplicates()
print("\n#Cleaning from Duplicates")
final_len = len(df)
print("\nFinal length after duplicates deletion:",final_len)

"""Standartize text inputs (to lower-case string-based feature entries)"""

text_columns = df.select_dtypes(include=['object']).columns
for col in text_columns:
    df[col] = df[col].astype(str).str.strip().str.lower()
display(df.head())

"""Dataset Description

Descriptive statistics for numerical variables
"""

print(df.columns.tolist())

numeric_columns = [
    "age",
    "watch_hours",
    "last_login_days",
    "number_of_profiles"
]

numeric_statistics = df[numeric_columns].describe().T

descriptive_statistics = []
for column in numeric_columns:
    # Coerce to numeric and drop missing values
    data = pd.to_numeric(df[column], errors="coerce").dropna()

    # Skip if column is empty after dropping NaNs
    if data.empty:
        continue

    # Calculate Mode cleanly
    mode_values = data.mode()
    if len(mode_values) == 1:
        mode = mode_values.iloc[0]
    elif len(mode_values) > 1:
        mode = ", ".join([f"{val:.4f}" if isinstance(val, (float, np.floating)) else str(val) for val in mode_values])
    else:
        mode = np.nan

    # Quartiles
    q1 = data.quantile(0.25)
    median = data.quantile(0.50)
    q3 = data.quantile(0.75)

    # Minimum and Maximum
    minimum = data.min()
    maximum = data.max()

    # Range and IQR
    data_range = maximum - minimum
    iqr = q3 - q1

    descriptive_statistics.append({
        "Variable": column,
        "Count": len(data),
        "Mean": data.mean(),
        "Median": median,
        "Mode": mode,
        "Minimum": minimum,
        "Q1 (25%)": q1,
        "Q2 (50%)": median,
        "Q3 (75%)": q3,
        "Maximum": maximum,
        "Range": data_range,
        "Interquartile Range (IQR)": iqr,
        "Variance": data.var(),
        "Standard Deviation": data.std(),
        "Skewness": data.skew(),
        "Kurtosis": data.kurt()
    })

# Convert list of dicts to DataFrame
descriptive_statistics_df = pd.DataFrame(descriptive_statistics)

# Round numeric output columns for clean display
numeric_stat_cols = descriptive_statistics_df.select_dtypes(include=[np.number]).columns
descriptive_statistics_df[numeric_stat_cols] = descriptive_statistics_df[numeric_stat_cols].round(3)

display(descriptive_statistics_df)

"""Frequency tables for categorical variables"""

categorical_columns = [
    "gender",
    "subscription_type",
    "region",
    "device",
    "payment_method",
    "favorite_genre"
]

for column in categorical_columns:

    print("\n" + "=" * 60)
    print(f"{column}")
    print("=" * 60)

    frequency_table = df[column].value_counts(dropna=False).to_frame(
        name="Frequency"
    )

    frequency_table["Percentage (%)"] = (
        frequency_table["Frequency"] / len(df) * 100
    )

    display(frequency_table)

"""Cross tabulations (Crosstabs)

Random
"""

crosstab_pairs = [(col, "churned") for col in categorical_columns if col != "churned"]

for row_variable, column_variable in crosstab_pairs:

    print("\n" + "=" * 70)
    print(
        f"Crosstab (frequencies): {row_variable} × {column_variable}"
    )
    print("=" * 70)

    crosstab = pd.crosstab(
        df[row_variable],
        df[column_variable]
    )

    display(crosstab)

    print("\n" + "=" * 70)
    print(
        f"Crosstab (total percentages): {row_variable} × {column_variable}"
    )
    print("=" * 70)

    crosstab_total_percent = pd.crosstab(
        df[row_variable],
        df[column_variable],
        normalize="all"
    ) * 100

    display(crosstab_total_percent.round(2))

"""---------------------------------------------------------------

z-scores
"""

# Calculate z-scores for all numerical variables

z_scores = pd.DataFrame(
    stats.zscore(
        df[numeric_columns],
        nan_policy="omit"
    ),
    columns=numeric_columns,
    index=df.index
)

print("z-scores for the numerical variables:")
display(z_scores.head())


# z-scores summary

z_score_summary = pd.DataFrame({
    "Variable": numeric_columns,
    "Mean of z-scores": [
        z_scores[column].mean()
        for column in numeric_columns
    ],
    "Std of z-scores": [
        z_scores[column].std()
        for column in numeric_columns
    ],
    "Minimum z-score": [
        z_scores[column].min()
        for column in numeric_columns
    ],
    "Maximum z-score": [
        z_scores[column].max()
        for column in numeric_columns
    ]
})

display(z_score_summary.round(4))

"""Detecting outliers using z-scores"""

Z_THRESHOLD = 3

z_outlier_flags = pd.DataFrame(
    False,
    index=df.index,
    columns=numeric_columns
)

for column in numeric_columns:
    z_outlier_flags[column] = z_scores[column].abs() > Z_THRESHOLD

# Number of potential outliers for each variable
z_outlier_summary = pd.DataFrame({
    "Variable": numeric_columns,
    "Potential outliers": [
        z_outlier_flags[column].sum()
        for column in numeric_columns
    ]
})

z_outlier_summary["Percentage (%)"] = (
    z_outlier_summary["Potential outliers"]
    / len(df) * 100
)

display(z_outlier_summary.round(2))


# z-score outlier observations

for column in numeric_columns:

    outlier_indices = z_outlier_flags.index[
        z_outlier_flags[column]
    ]

    if len(outlier_indices) > 0:

        print("\n" + "=" * 70)
        print(f"z-score outliers: {column}")
        print("=" * 70)

        outlier_table = df.loc[
            outlier_indices,
            [ column]
        ].copy()

        outlier_table["z-score"] = z_scores.loc[
            outlier_indices,
            column
        ]

        display(
            outlier_table.sort_values(
                "z-score"
            )
        )

    else:

        print(
            f"\n{column}: No observations with |z| > {Z_THRESHOLD}."
        )

"""Detecting outliers using the IQR method"""

iqr_outlier_flags = pd.DataFrame(
    False,
    index=df.index,
    columns=numeric_columns
)

iqr_summary = []

for column in numeric_columns:

    data = pd.to_numeric(
        df[column],
        errors="coerce"
    )

    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - 3 * iqr
    upper_bound = q3 + 3 * iqr

    flags = (
        (data < lower_bound) |
        (data > upper_bound)
    )

    iqr_outlier_flags[column] = flags

    iqr_summary.append({
        "Variable": column,
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower bound": lower_bound,
        "Upper bound": upper_bound,
        "Potential outliers": flags.sum(),
        "Percentage (%)": flags.mean() * 100
    })

iqr_summary = pd.DataFrame(iqr_summary)

display(iqr_summary.round(4))


# IQR outlier observations

for column in numeric_columns:

    outlier_indices = iqr_outlier_flags.index[
        iqr_outlier_flags[column]
    ]

    if len(outlier_indices) > 0:

        print("\n" + "=" * 70)
        print(f"IQR outliers: {column}")
        print("=" * 70)

        outlier_table = df.loc[
            outlier_indices,
            [column]
        ].copy()

        display(
            outlier_table.sort_values(
                by=column
            )
        )

    else:

        print(
            f"\n{column}: No IQR outliers detected."
        )

"""Compare the two outlier-detection methods"""

outlier_comparison = pd.DataFrame({
    "Variable": numeric_columns,
    "z-score outliers": [
        z_outlier_flags[column].sum()
        for column in numeric_columns
    ],
    "IQR outliers": [
        iqr_outlier_flags[column].sum()
        for column in numeric_columns
    ]
})

outlier_comparison["Difference"] = (
    outlier_comparison["z-score outliers"]
    - outlier_comparison["IQR outliers"]
)

display(outlier_comparison)

"""Box-and-whisker diagram (boxplot)"""

for column in numeric_columns:
    plt.figure(figsize=(9, 4))

    # Setting whis=3.0 flags only extreme outliers (> 3 * IQR)
    sns.boxplot(
        data=df,
        x=column,
        whis=3.0
    )

    plt.title(f"Box-and-Whisker Plot (Extreme Outliers) — {column}")
    plt.xlabel(column)
    plt.grid(True, axis="x", alpha=0.3)
    plt.show()

"""Outliers handling

*Recalculation of outliers : capping 'watch_hours' to end of quartile.*
"""

# Clip watch_hours at the 99th percentile threshold
upper_threshold = df['watch_hours'].quantile(0.99)
df['watch_hours'] = np.clip(df['watch_hours'], a_min=None, a_max=upper_threshold)

# Re-verify summary statistics after cleaning
print(f"Capped upper limit for watch_hours: {upper_threshold:.2f} hrs")
display(df[['watch_hours']].describe())

"""Detecting Outliers once-again"""

iqr_outlier_flags = pd.DataFrame(
    False,
    index=df.index,
    columns=numeric_columns
)

iqr_summary = []

for column in numeric_columns:

    data = pd.to_numeric(
        df[column],
        errors="coerce"
    )

    q1 = data.quantile(0.25)
    q3 = data.quantile(0.75)

    iqr = q3 - q1

    lower_bound = q1 - 3 * iqr
    upper_bound = q3 + 3 * iqr

    flags = (
        (data < lower_bound) |
        (data > upper_bound)
    )

    iqr_outlier_flags[column] = flags

    iqr_summary.append({
        "Variable": column,
        "Q1": q1,
        "Q3": q3,
        "IQR": iqr,
        "Lower bound": lower_bound,
        "Upper bound": upper_bound,
        "Potential outliers": flags.sum(),
        "Percentage (%)": flags.mean() * 100
    })

iqr_summary = pd.DataFrame(iqr_summary)

display(iqr_summary.round(4))


# IQR outlier observations

for column in numeric_columns:

    outlier_indices = iqr_outlier_flags.index[
        iqr_outlier_flags[column]
    ]

    if len(outlier_indices) > 0:

        print("\n" + "=" * 70)
        print(f"IQR outliers: {column}")
        print("=" * 70)

        outlier_table = df.loc[
            outlier_indices,
            [column]
        ].copy()

        display(
            outlier_table.sort_values(
                by=column
            )
        )

    else:

        print(
            f"\n{column}: No IQR outliers detected."
        )

"""Display the number of outliers"""

outlier_counts_df = iqr_summary[["Variable", "Potential outliers", "Percentage (%)"]]
print(outlier_counts_df)

"""Box-and-whisker diagram (boxplot)"""

for column in numeric_columns:
    plt.figure(figsize=(9, 4))

    # Setting whis=3.0 flags only extreme outliers (> 3 * IQR)
    sns.boxplot(
        data=df,
        x=column,
        whis=3.0
    )

    plt.title(f"Box-and-Whisker Plot (Extreme Outliers) — {column}")
    plt.xlabel(column)
    plt.grid(True, axis="x", alpha=0.3)
    plt.show()

"""Deletion of Final Outliers"""

# # Drop rows where any numeric column flagged True
# df_old=df.copy()
# df = df[~iqr_outlier_flags.any(axis=1)]

# print(f"Original shape: {df_old.shape}")
# print(f"Cleaned shape:  {df.shape}")

"""-------------------------------------------------------------

**Data Visualisation**

For continious data *<'age', 'watch_hours', 'last_login_days', 'avg_watch_time_per_day'>*
"""

num_cols = df[['age', 'watch_hours', 'last_login_days']].columns

for col in num_cols:

    mean_val = df[col].mean()
    median_val = df[col].median()
    skew_val = df[col].skew()

    print("-" * 60)
    print(f"Column: {col}")
    print(f"Skewness: {skew_val:.4f}")
    print(f"Mean:     {mean_val:.2f}")
    print(f"Median:   {median_val:.2f}")

    plt.figure(figsize=(8, 3.5))
    sns.histplot(df[col], kde=True)
    plt.axvline(
        mean_val,
        color="red",
        linestyle="--",
        linewidth=2,
        label=f"Mean ({mean_val:.2f})",
    )
    plt.axvline(
        median_val,
        color="green",
        linestyle="-",
        linewidth=2,
        label=f"Median ({median_val:.2f})",
    )
    plt.title(f"Distribution Diagnostic: {col}")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""For Multi-Categorical Variables *<'gender', 'subscription_type', 'region', 'device', 'favorite_genre'>*"""

cat_cols = df[['gender', 'subscription_type', 'region', 'number_of_profiles', 'device', 'favorite_genre']].columns

for col in cat_cols:
    # Calculate counts and percentage proportions
    val_counts = df[col].value_counts(dropna=False)
    val_pcts = df[col].value_counts(normalize=True, dropna=False) * 100

    summary_df = pd.DataFrame(
        {"Count": val_counts, "Percentage (%)": val_pcts.round(2)}
    )

    print("-" * 60)
    print(f"Column: {col}")
    print(summary_df)

    # Plot distribution
    plt.figure(figsize=(8, 4))
    ax = sns.countplot(
        data=df,
        x=col,
        order=val_counts.index,
        palette="viridis",
        hue=col,
        legend=False,
    )

    # Annotate bars with frequency count and percentage
    total = len(df[col].dropna())
    for p in ax.patches:
        height = p.get_height()
        if height > 0:
            percentage = f"{(height / total) * 100:.1f}%"
            ax.annotate(
                f"{int(height)}\n({percentage})",
                (p.get_x() + p.get_width() / 2.0, height),
                ha="center",
                va="bottom",
                xytext=(0, 4),
                textcoords="offset points",
            )

    plt.title(f"Category Distribution: {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.xticks(rotation=45 if df[col].nunique() > 5 else 0)
    plt.tight_layout()
    plt.show()

"""Pie Representation for Binary Variable (Churned)"""

churn_counts = df['churned'].value_counts()

plt.figure(figsize=(6, 6))
colors = ["#F59C27", "#27E0F5"]

plt.pie(
    churn_counts,
    labels=churn_counts.index,
    autopct="%1.1f%%",
    startangle=90,
    colors=colors[: len(churn_counts)],
    explode=[0.05] + [0] * (len(churn_counts) - 1),
    shadow=True,
    textprops={"fontsize": 11, "weight": "bold"},
)

plt.title("Netflix Account Churn Distribution", fontsize=14, pad=20)
plt.legend(title="Status", loc="upper right")
plt.tight_layout()
plt.show()

"""Correlation coefficient (r)"""

# Correlation matrix
correlation_matrix = df[numeric_columns].corr(method="pearson")

display(correlation_matrix.round(4))

# Correlation heatmap

plt.figure(figsize=(10, 7))

sns.heatmap(
    correlation_matrix,
    annot=True,
    fmt=".3f",
    cmap="coolwarm",
    center=0,
    vmin=-1,
    vmax=1
)

plt.title("Pearson Correlation Matrix")
plt.show()

"""Encode multi-categorical into values"""

# Select categorical columns to encode
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()

# Make a copy of the dataframe to avoid modifying original in-place if needed
df_encoded = df.copy()

# Initialize and fit OrdinalEncoder
encoder = OrdinalEncoder()
encoded_values = encoder.fit_transform(df_encoded[categorical_cols])

# Convert to 1-based index integer encoding
for i, col in enumerate(categorical_cols):
    df_encoded[col] = encoded_values[:, i].astype(int) + 1

# Ensure any remaining categorical columns are converted
df_encoded = pd.get_dummies(df_encoded, dtype=int)
display(df_encoded.head())

"""Correlation Coefficients to watch_hours"""

corr_matrix = df_encoded.corr()

# 3. Correlation with watch_hours
watch_corr = (
    corr_matrix["watch_hours"].drop("watch_hours").sort_values(ascending=False)
)

print("=== Correlation with watch_hours ===")
print(watch_corr)

"""Correlation Coefficients to churned"""

# Correlation of all features with churned
churn_corr = (
    corr_matrix["churned"].drop("churned").sort_values(ascending=False)
)
print("\n=== Correlation with churned ===")
print(churn_corr)

"""Correlation Coefficients to age"""

# Correlation of all features with age
age_corr = (
    corr_matrix["age"].drop("age").sort_values(ascending=False)
)
print("\n=== Correlation with age ===")
print(age_corr)

"""Representation"""

fig, axes = plt.subplots(1, 3, figsize=(16, 8))

# Plot Watch Hours correlations
sns.barplot(
    x=watch_corr.values,
    y=watch_corr.index,
    ax=axes[0],
    palette="crest",
    hue=watch_corr.index,
    legend=False,
)
axes[0].set_title("Feature Correlation with watch_hours")
axes[0].set_xlabel("Pearson Correlation Coefficient")
axes[0].set_ylabel("Feature")

# Plot Churned correlations
sns.barplot(
    x=churn_corr.values,
    y=churn_corr.index,
    ax=axes[1],
    palette="flare",
    hue=churn_corr.index,
    legend=False,
)
axes[1].set_title("Feature Correlation with churned")
axes[1].set_xlabel("Pearson Correlation Coefficient")
axes[1].set_ylabel("Feature")

# Plot Age correlations (FIXED: changed ax=axes[1] to ax=axes[2])
sns.barplot(
    x=age_corr.values,
    y=age_corr.index,
    ax=axes[2],
    palette="cubehelix",
    hue=age_corr.index,
    legend=False,
)
axes[2].set_title("Feature Correlation with age")
axes[2].set_xlabel("Pearson Correlation Coefficient")
axes[2].set_ylabel("Feature")

plt.tight_layout()
plt.show()

"""#TASK 2
**Hypothesis testing and statistical inference**

Print Functions
"""

ALPHA = 0.05

def decision(p_value, alpha=ALPHA):
    return "Reject H0" if p_value < alpha else "Do not reject H0"

def print_result(test_name, h0, h1, statistic_name, statistic, p_value, alpha=ALPHA):
    print("=" * 80)
    print(test_name)
    print("-" * 80)
    print("H0:", h0)
    print("H1:", h1)
    print(f"{statistic_name} = {statistic:.4f}")
    print(f"p-value = {p_value:.6f}")
    print(f"alpha = {alpha}")
    print("Decision:", decision(p_value, alpha))
    if p_value < alpha:
        print("Interpretation: There is statistically significant evidence against H0.")
    else:
        print("Interpretation: There is not sufficient statistical evidence against H0.")

"""**Shapiro-Wilk test for Normality**"""

x = df["watch_hours"].dropna()

#Normality Check via Shapiro-Wilk

stat, p_value = stats.shapiro(x)

print_result(
    test_name = "Shapiro-Wilk test for normality",
    h0 = "The population distribution is normal",
    h1 = "The population distribution is not normal",
    statistic_name = "w",
    statistic = stat,
    p_value = p_value
)

"""Normalization via logarithm"""

df["log_watch_hours"] = np.log1p(df["watch_hours"])
display(df.head())

"""Display Data"""

num_cols = df[['log_watch_hours']].columns

for col in num_cols:

    mean_val = df[col].mean()
    median_val = df[col].median()
    skew_val = df[col].skew()

    print("-" * 60)
    print(f"Column: {col}")
    print(f"Skewness: {skew_val:.4f}")
    print(f"Mean:     {mean_val:.2f}")
    print(f"Median:   {median_val:.2f}")

    plt.figure(figsize=(8, 3.5))
    sns.histplot(df[col], kde=True)
    plt.axvline(
        mean_val,
        color="red",
        linestyle="--",
        linewidth=2,
        label=f"Mean ({mean_val:.2f})",
    )
    plt.axvline(
        median_val,
        color="green",
        linestyle="-",
        linewidth=2,
        label=f"Median ({median_val:.2f})",
    )
    plt.title(f"Distribution Diagnostic: {col}")
    plt.legend()
    plt.tight_layout()
    plt.show()

"""New Shapiro-Wilk Test"""

x = df["log_watch_hours"].dropna()

#Normality Check via Shapiro-Wilk

stat, p_value = stats.shapiro(x)

print_result(
    test_name = "Shapiro-Wilk test for normality",
    h0 = "The population distribution is normal",
    h1 = "The population distribution is not normal",
    statistic_name = "w",
    statistic = stat,
    p_value = p_value
)

"""**One Sample T-Test**

Is the population average monthly streaming time (watch_hours) equal to 11.0 hours?
$\begin{cases}
H_0: \mu = 11.0 \\
H_1: \mu \neq 11.0
\end{cases}$
"""

#One-Sample t-test
x = df["watch_hours"].dropna()

mu0 =11.0

# Two-sided alternative
t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='two-sided')

# Right-sided alternative
#t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='greater')

#Left-sided alternative
#t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='less')

print_result(
    test_name = "One sample t-test",
    h0 = "μ = 11.0",
    h1 = "μ ≠ 11.0",
    statistic_name = "t",
    statistic = t_stat,
    p_value = p_value
)

print(f"Sample mean = {x.mean():.2f}")
print(f"Sample standard deviation = {x.std(ddof=1):.2f}")
print(f"Sample size = {len(x)}")

#One-Sample t-test
x = df["age"].dropna()

mu0 =12.0

# Two-sided alternative
# t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='two-sided')

# Right-sided alternative
t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='greater')

#Left-sided alternative
#t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='less')

print_result(
    test_name = "One sample t-test",
    h0 = "μ = 43.0",
    h1 = "μ ≠ 43.0",
    statistic_name = "t",
    statistic = t_stat,
    p_value = p_value
)

print(f"Sample mean = {x.mean():.2f}")
print(f"Sample standard deviation = {x.std(ddof=1):.2f}")
print(f"Sample size = {len(x)}")

#One-Sample t-test
x = df["log_watch_hours"].dropna()

mu0 = 2.0

# Two-sided alternative
t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='two-sided')

# Right-sided alternative
# t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='greater')

#Left-sided alternative
# t_stat, p_value = stats.ttest_1samp(x, popmean=mu0, alternative='less')

print_result(
    test_name = "One sample t-test",
    h0 = "μ = 2.0",
    h1 = "μ ≠ 2.0",
    statistic_name = "t",
    statistic = t_stat,
    p_value = p_value
)

print(f"Sample mean = {x.mean():.2f}")
print(f"Sample standard deviation = {x.std(ddof=1):.2f}")
print(f"Sample size = {len(x)}")

"""**Hypothesis test for the population proportion**

Is the population proportion of churn rate equal to **0.50** (or 50%)?

$\begin{cases}
H_0: p = 0.50 \\
H_1: p \neq 0.50
\end{cases}$
"""

churn = df["churned"].dropna()
success = (churn == 1).sum()
n = len(churn)
p0 = 0.5

# Two-sided alternative
z_stat, p_value = proportions_ztest(count=success, nobs=n, value=p0, alternative="two-sided")

# Right-sided alternative
# z_stat, p_value = proportions_ztest(count=success, nobs=n, value=p0, alternative="larger")

# Left-sided alternative
# z_stat, p_value = proportions_ztest(count=success, nobs=n, value=p0, alternative="smaller")

print_result(
    test_name = "One sample population proportion test",
    h0 = "p = 0.50",
    h1 = "p ≠ 0.50",
    statistic_name = "z",
    statistic = z_stat,
    p_value = p_value
)

print(f"Observed proportion (churned = 1) = {success/n:.4f}")
print(f"Total churned subscribers = {success}")
print(f"Total subscribers (n) = {n}")

"""**Hypothesis testing for correlation**

Is there a statistically significant linear correlation between the **watch_hours** of customers and their **last_login_days amount**?

$\begin{cases}
H_0: \rho = 0 \\
H_1: \rho \neq 0
\end{cases}$

Variables:
- `watch_hours`
- `last_login_days`

The Shapiro-Wilk test is performed for both variables before testing for correlation.

Shapiro
"""

x = df["watch_hours"].dropna()

stat, p_value = stats.shapiro(x)

print_result(
    test_name = "Shapiro-Wilk test for normality: watch_hours",
    h0 = "The population distribution is normal",
    h1 = "The population distribution is not normal",
    statistic_name = "w",
    statistic = stat,
    p_value = p_value
)

x = df["last_login_days"].dropna()

stat, p_value = stats.shapiro(x)

print_result(
    test_name = "Shapiro-Wilk test for normality: last_login_days",
    h0 = "The population distribution is normal",
    h1 = "The population distribution is not normal",
    statistic_name = "w",
    statistic = stat,
    p_value = p_value
)

"""Correlation testing"""

corr_data = df[["watch_hours", "last_login_days"]].dropna()

r, p_value = stats.pearsonr(corr_data["watch_hours"], corr_data["last_login_days"], alternative='two-sided')

print_result(
    test_name = "Hypothesis test for correlation",
    h0 = "ρ = 0",
    h1 = "ρ ≠ 0",
    statistic_name = "r",
    statistic = r,
    p_value = p_value
)

print(f"n = {len(corr_data)}")

"""Presentation"""

sns.regplot(
    data=corr_data,
    x="watch_hours",
    y="last_login_days",
    ci=None
)
plt.title("watch_hours vs last_login_days")
plt.show()

"""**Two independent samples t-test**


Do active subscribers (churned = 0) and churned subscribers (churned = 1) have different average watch_hours?

$\begin{cases}
H_0: \mu_x = \mu_y \\
H_1: \mu_x \neq \mu_y
\end{cases}$

Data Selection
"""

ind_data = df[["churned", "watch_hours"]].dropna()

active = ind_data.loc[ind_data["churned"] == 0, "watch_hours"]
churned = ind_data.loc[ind_data["churned"] == 1, "watch_hours"]

print(f"Active: n = {len(active)}, mean = {active.mean():.4f}, var = {active.var(ddof=1):.4f}")
print(f"Churned: n = {len(churned)}, mean = {churned.mean():.4f}, var = {churned.var(ddof=1):.4f}")

"""Shapiro-Wilk Test"""

# Test normality using Shapiro-Wilk test

stat, p_value = stats.shapiro(active)

print_result(
    test_name = "Shapiro-Wilk test for normality: Watch hours for active",
    h0 = "The population distribution is normal",
    h1 = "The population distribution is not normal",
    statistic_name = "w",
    statistic = stat,
    p_value = p_value
)

stat, p_value = stats.shapiro(churned)

print_result(
    test_name = "Shapiro-Wilk test for normality: Watch hours for churned",
    h0 = "The population distribution is normal",
    h1 = "The population distribution is not normal",
    statistic_name = "w",
    statistic = stat,
    p_value = p_value
)

"""Test equality of variances using Levene's test"""

print("\n--- Levene's test for equality of variances ---")

levene_stat, levene_p = stats.levene(active, churned, center="median")

print(f"Levene statistic = {levene_stat:.4f}")
print(f"Levene p-value = {levene_p:.4f}")

if levene_p < ALPHA:
    print(
        f"p-value < {ALPHA}: Reject H0."
    )
    print(
        "There is evidence that the population variances are different."
    )
    equal_variances = False
else:
    print(
        f"p-value >= {ALPHA}: Do not reject H0."
    )
    print(
        "There is insufficient evidence that the population variances are different."
    )
    equal_variances = True

"""Independent samples t-test"""

# Select and perform the appropriate t-test

print("\n--- Independent samples t-test ---")

if equal_variances:
    # Equal variances assumed
    t_stat, p_value = stats.ttest_ind(active, churned, equal_var=True)
    selected_test = "Independent samples t-test (equal variances assumed)"
else:
    # Equal variances not assumed
    t_stat, p_value = stats.ttest_ind(active, churned, equal_var=False)
    selected_test = "Welch's independent samples t-test"

print(f"Selected test: {selected_test}")

print_result(
    test_name = "Two independent-samples t-test",
    h0 = "μ_x = μ_y",
    h1 = "μ_x ≠ μ_y",
    statistic_name = "t",
    statistic = t_stat,
    p_value = p_value
)

print(f"Active sample mean = {active.mean():.4f}, n = {len(active)}")
print(f"Churned sample mean = {churned.mean():.4f}, n = {len(churned)}")

"""**Paired samples t-test** (SKIP - We don't have two continious data before and after)

**Equality of two population proportions**

Are the population proportions of customers with inactive accounts buying **basic subscription** and **premium subscription** equal?

$\begin{cases}
H_0: p_A = p_B \\
H_1: p_A \neq p_B
\end{cases}$


Variables:
- `subscription_type == basic`
- `subscription_type == premium`
for `churned`
"""

basic_subscribers = df[df["subscription_type"] == "basic"]["churned"].dropna()
premium_subscribers = df[df["subscription_type"] == "premium"]["churned"].dropna()

success_basic = (basic_subscribers == 1).sum()
success_premium = (premium_subscribers == 1).sum()

n_basic = len(basic_subscribers)
n_premium = len(premium_subscribers)

z_stat, p_value = proportions_ztest(
    count=[success_basic, success_premium],
    nobs=[n_basic, n_premium],
    alternative="two-sided"
)

print_result(
    test_name = "Equality of two population proportions: Churn Rate (Basic vs Premium)",
    h0 = "p_A = p_B",
    h1 = "p_A ≠ p_B",
    statistic_name = "z",
    statistic = z_stat,
    p_value = p_value
)

print(f"Basic tier churn rate = {success_basic/n_basic:.4f} (n={n_basic})")
print(f"Premium tier churn rate = {success_premium/n_premium:.4f} (n={n_premium})")

"""**Chi-square (χ²) goodness-of-fit test**


Is the subscriber distribution across subscription_type evenly split across tiers (33.3% Basic, 33.3% Standard, 33.3% Premium)?

- Basic = 0.33 (33%)
- Standard = 0.33 (33%)
- Premium = 0.33 (33%)

$\begin{cases}
H_0: p_1 = 0.33, p_2 = 0.33, p_3 = 0.33 \\
H_1: \text{At least one } p_i \neq p_{i}^{0} (i=1, 2, ..., n)
\end{cases}$


Variable: `subscription_type`
"""

tiers = df["subscription_type"].dropna().str.strip()

categories = ["basic", "standard", "premium"]
observed = tiers.value_counts().reindex(categories, fill_value=0).values
hypothesized_proportions = np.array([1/3, 1/3, 1/3])
expected = tiers.size * hypothesized_proportions

chi2_stat, p_value = stats.chisquare(observed, f_exp=expected)

print_result(
    test_name="Chi-square goodness-of-fit test: Subscription Tiers",
    h0="p_Basic = 0.333, p_Standard = 0.333, p_Premium = 0.333",
    h1="At least one tier proportion differs",
    statistic_name="χ²",
    statistic=chi2_stat,
    p_value=p_value
)

display(pd.DataFrame({
    "Category": categories,
    "Observed": observed,
    "Expected": expected,
    "Observed Proportion": observed / observed.sum(),
    "Expected Proportion": hypothesized_proportions
}))

"""**Chi-square (χ²) goodness-of-fit test**


Is the subscriber distribution across subscription_type evenly split across tiers (33.3% Basic, 33.3% Standard, 33.3% Premium)?

- Basic = 0.33 (33%)
- Standard = 0.33 (33%)
- Premium = 0.33 (33%)

$\begin{cases}
H_0: p_1 = 0.33, p_2 = 0.33, p_3 = 0.33 \\
H_1: \text{At least one } p_i \neq p_{i}^{0} (i=1, 2, ..., n)
\end{cases}$


Variable: `subscription_type`
"""

tiers = df["region"].dropna().str.strip()

categories = ["africa", "asia", "europe","north america", "oceania", "south america"]
observed = tiers.value_counts().reindex(categories, fill_value=0).values
hypothesized_proportions = np.array([1/6,1/6,1/6,1/6,1/6,1/6])
expected = tiers.size * hypothesized_proportions

chi2_stat, p_value = stats.chisquare(observed, f_exp=expected)

print_result(
    test_name="Chi-square goodness-of-fit test: Regions",
    h0="r_Africa = 0.16, r_Asia = 0.16, r_Europe = 0.16, r_NorthAmerica = 0.16, r_Oceania=0.16 , r_SouthAmerica=0.16",
    h1="At least one tier proportion differs",
    statistic_name="χ²",
    statistic=chi2_stat,
    p_value=p_value
)

display(pd.DataFrame({
    "Category": categories,
    "Observed": observed,
    "Expected": expected,
    "Observed Proportion": observed / observed.sum(),
    "Expected Proportion": hypothesized_proportions
}))

"""**Chi-square (χ²) test of independence**

Is **churn** status independent of having a specific **payment** option?

$\begin{cases}
H_0: \text{Payment method and Churn satus are independent} \\
H_1: \text{Payment method and Churn satus are dependent}
\end{cases}$

Variables:
- `payment_method`
- `churned`
"""

ind_table = pd.crosstab(df["payment_method"], df["churned"])

chi2_stat, p_value, dof, expected = stats.chi2_contingency(ind_table)

print_result(
    test_name="Chi-square test of independence: Payment Method vs Churn",
    h0="Payment Method and Churn are independent",
    h1="Payment Method and Churn are dependent",
    statistic_name = "χ²",
    statistic = chi2_stat,
    p_value = p_value
)

print("\nObserved frequencies:")
display(ind_table)
print("Expected frequencies:")
display(pd.DataFrame(expected, index=ind_table.index, columns=ind_table.columns))

"""**Chi-square (χ²) test of homogeneity**

Is the distribution of **subscription type** the same across the four **regions**?

$\begin{cases}
H_0: \text{The distribution of purchase decision is the same across the four regions} \\
H_1: \text{At least one region has a different distribution}
\end{cases}$


Variables:
- `region`
- `subscription_type`
"""

hom_table = pd.crosstab(df["region"], df["subscription_type"])

chi2_stat, p_value, dof, expected = stats.chi2_contingency(hom_table)

print_result(
    test_name = "Chi-square test of homogeneity",
    h0 = "Purchase decision has the same distribution across regions",
    h1 = "At least one region has a different distribution",
    statistic_name = "χ²",
    statistic = chi2_stat,
    p_value = p_value
)

print("\nObserved frequencies:")
display(hom_table)
print("Expected frequencies:")
display(pd.DataFrame(expected, index=hom_table.index, columns=hom_table.columns))

"""#TASK 3
**Predictive modelling & regression analysis**

Define constants
"""

ALPHA = 0.05
RANDOM_STATE = 42
TEST_SIZE = 0.20

"""**Single-Variable Linear Regression**

Data Preparation and display summary statistics

```markdown
Independent Variable (X) : "number_of_profiles", "churned", "age", "last_login_days", "subscription_type_encoded" (base for prediction)

Dependent Variable (Y) : "watch_hours" (which would be predicted)
```

Encode into 1,2,3 for subscription_type
"""

# Map subscription_type to 1, 2, 3
subscription_mapping = {'basic': 1, 'standard': 2, 'premium': 3}
df['subscription_type_encoded'] = df['subscription_type'].map(subscription_mapping)

# Display the updated DataFrame
display(df.head())

linear_regression_features = ["number_of_profiles", "churned", "age", "last_login_days", "subscription_type_encoded"]
predicted_feature = "log_watch_hours"

"""Feature Statistics"""

simple_data_packs = []

for feature in linear_regression_features:
    print("\n" + ("-" * 40))
    print(f"Feature: {feature}")

    # Make sure we select the columns and create a clean copy
    simple_data = df[[feature, predicted_feature]].copy()

    simple_data[feature] = pd.to_numeric(simple_data[feature], errors="coerce")
    simple_data[predicted_feature] = pd.to_numeric(simple_data[predicted_feature], errors="coerce")

    # Store the clean pair in our pack list
    simple_data_packs.append(simple_data)

    print("Dataset shape:", simple_data.shape)
    display(simple_data.head())

    print("Summary statistics:")
    display(simple_data.describe())
    print("-" * 40)

"""Corelation coefficient (Pearson correlation) and significance test"""

for number in range(len(linear_regression_features)):
  print("\n")
  print("-"*30)
  simple_data = simple_data_packs[number]
  feature = linear_regression_features[number]
  x = simple_data[feature]
  y = simple_data[predicted_feature]
  print(feature)
  r, correlation_p = stats.pearsonr(x, y)

  print("Pearson correlation test")
  print(f"Correlation coefficient (r) = {r:.4f}")
  print(f"p-value = {correlation_p:.6f}")

  if correlation_p < ALPHA:
      print(f"p-value < {ALPHA}: Reject H0. There is evidence of a statistically significant linear correlation.")
  else:
      print(f"p-value >= {ALPHA}: Do not reject H0. There is insufficient evidence of a statistically significant linear correlation.")

"""Scatter Plot"""

for number in range(len(linear_regression_features)):
    print("\n")
    print("-"*30)
    simple_data = simple_data_packs[number]
    feature = linear_regression_features[number]

    plt.figure(figsize=(9, 6))
    plt.scatter(simple_data[feature], simple_data[predicted_feature], alpha=0.6)
    plt.xlabel(f"{feature}")
    plt.ylabel(predicted_feature)
    plt.title(f"{feature} vs. {predicted_feature}")
    plt.grid(True, alpha=0.3)
    plt.show()

"""Train-test split and model fitting"""

simple_model_OSL_packs = []
simple_model_packs = []
train_test_tuples = []
for number in range(len(linear_regression_features)):
  print("\n")
  print("-"*30)
  simple_data = simple_data_packs[number]
  feature = linear_regression_features[number]

  X = simple_data[[feature]]
  y = simple_data[predicted_feature]

  X_train, X_test, y_train, y_test = train_test_split(
      X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE
  )


  print("Training observations:", len(X_train))
  print("Testing observations:", len(X_test))

  simple_model = LinearRegression()
  simple_model.fit(X_train, y_train)
  y_pred = simple_model.predict(X_test)

  intercept = simple_model.intercept_
  slope = simple_model.coef_[0]

  print("\nSimple Linear Regression model coefficients:")
  print(f"Intercept (a) = {intercept:.6f}")
  print(f"Slope (b) = {slope:.6f}")
  print(f"Estimated regression equation: {predicted_feature} = {intercept:.4f} + {slope:.6f} × {feature}")

  # OLS Model
  X_train_sm = sm.add_constant(X_train)
  simple_model_OLS = sm.OLS(y_train, X_train_sm).fit()
  simple_model_OSL_packs.append(simple_model_OLS)
  simple_model_packs.append(simple_model)

  train_test_tuples.append((X_train, X_test, y_train, y_test))

  print(simple_model_OLS.summary())

"""Testing for significance (t-test) + Testing for significance (F-test)"""

for number in range(len(linear_regression_features)):
  print("\n")
  print("-"*30)
  simple_data = simple_data_packs[number]
  feature = linear_regression_features[number]
  simple_model_OLS = simple_model_OSL_packs[number]
  simple_model = simple_model_packs[number]


  print(f"t-test for the {feature} coefficient")
  print("H0: b = 0")
  print("H1: b ≠ 0")

  t_stat_age = simple_model_OLS.tvalues[feature]
  p_value_age = simple_model_OLS.pvalues[feature]

  print(f"t-statistic = {t_stat_age:.4f}")
  print(f"p-value = {p_value_age:.6f}")

  if p_value_age < ALPHA:
      print(f"p-value < {ALPHA}: Reject H0. {feature} is a statistically significant predictor of {predicted_feature}.")
  else:
      print(f"p-value >= {ALPHA}: Do not reject H0. There is insufficient evidence that {feature} is a statistically significant predictor.")

  print("F-test for the overall regression model")
  print("H0: b = 0")
  print("H1: b ≠ 0")

  f_stat = simple_model_OLS.fvalue
  f_p_value = simple_model_OLS.f_pvalue

  print(f"F-statistic = {f_stat:.4f}")
  print(f"p-value = {f_p_value:.6f}")

  if f_p_value < ALPHA:
      print(f"p-value < {ALPHA}: Reject H0. The regression model is statistically significant.")
  else:
      print(f"p-value >= {ALPHA}: Do not reject H0. There is insufficient evidence that the regression model is statistically significant.")

"""Regression line"""

for number in range(len(linear_regression_features)):
  simple_data = simple_data_packs[number]
  feature = linear_regression_features[number]
  simple_model = simple_model_packs[number]
  X_train, X_test, y_train, y_test = train_test_tuples[number]


  plot_data = simple_data.copy()
  plot_data["Predicted"] = simple_model.predict(plot_data[[feature]])
  plot_data = plot_data.sort_values(feature)

  plt.figure(figsize=(9, 6))
  plt.scatter(X_train[feature], y_train, alpha=0.4, label="Training data")
  plt.scatter(X_test[feature], y_test, alpha=0.6, label="Test data")
  plt.plot(plot_data[feature], plot_data["Predicted"], color="red", linewidth=2, label="Fitted regression line")
  plt.xlabel(f"{feature}")
  plt.ylabel(f"{predicted_feature}")
  plt.title(f"Simple Linear Regression — {feature} vs. {predicted_feature}")
  plt.legend()
  plt.grid(True, alpha=0.3)
  plt.show()

"""Predict the test observations"""

simple_predictions_packs = []
y_pred_packs = []
for number in range(len(linear_regression_features)):
  simple_data = simple_data_packs[number]
  feature = linear_regression_features[number]
  simple_model = simple_model_packs[number]
  X_train, X_test, y_train, y_test = train_test_tuples[number]
  print("\n")
  print("-"*30)
  print(f"Feature: {feature}")

  y_pred = simple_model.predict(X_test)
  simple_predictions = X_test.copy()
  simple_predictions["Actual"] = y_test.values
  simple_predictions["Predicted"] = y_pred
  simple_predictions["Residual"] = simple_predictions["Actual"] - simple_predictions["Predicted"]
  simple_predictions_packs.append(simple_predictions)
  y_pred_packs.append(y_pred)
  display(simple_predictions.head(15))

"""Actual vs. predicted plot"""

for number in range(len(linear_regression_features)):
  simple_data = simple_data_packs[number]
  feature = linear_regression_features[number]
  simple_predictions = simple_predictions_packs[number]
  print("\n" + "-"*30)
  print(f"Feature: {feature}")

  plt.figure(figsize=(8, 6))
  plt.scatter(simple_predictions["Actual"], simple_predictions["Predicted"], alpha=0.7)

  min_val = min(simple_predictions["Actual"].min(), simple_predictions["Predicted"].min())
  max_val = max(simple_predictions["Actual"].max(), simple_predictions["Predicted"].max())
  plt.plot([min_val, max_val], [min_val, max_val], linestyle="--", color="red", label="Perfect prediction")

  plt.xlabel(f"Actual {predicted_feature}")
  plt.ylabel(f"Predicted {predicted_feature}")
  plt.title("Actual vs. Predicted Values — Simple Linear Regression")
  plt.legend()
  plt.grid(True, alpha=0.3)
  plt.show()

"""Predictive performance (model evaluation)"""

def calculate_mape(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    nonzero_mask = y_true != 0
    if nonzero_mask.sum() == 0:
        return np.nan
    return np.mean(np.abs((y_true[nonzero_mask] - y_pred[nonzero_mask]) / y_true[nonzero_mask])) * 100

for number in range(len(linear_regression_features)):
  X_train, X_test, y_train, y_test = train_test_tuples[number]
  y_pred = y_pred_packs[number]
  print("\n")
  print("-"*30)
  print(f"Feature: {linear_regression_features[number]}")

  mae = mean_absolute_error(y_test, y_pred)
  mse = mean_squared_error(y_test, y_pred)
  rmse = np.sqrt(mse)
  r_squared = r2_score(y_test, y_pred)
  mape = calculate_mape(y_test, y_pred)

  simple_metrics = pd.DataFrame({
      "Metric": ["MAE", "MSE", "RMSE", "MAPE (%)", "R-squared"],
      "Value": [mae, mse, rmse, mape, r_squared]
  })
  display(simple_metrics)

"""---------------------------------------------------------------

**Multi-Variable Linear Regression**

Prepare the data and display summary statistics

```markdown
Independent Variables (X) : age, last_login_days (base for prediction)

Dependent Variable (Y) : watch_hours (which would be predicted)
```
"""

numeric_columns = ["number_of_profiles", "churned", "age", "last_login_days", "subscription_type_encoded", predicted_feature]

multiple_data = df[numeric_columns].copy()

for column in numeric_columns:
    multiple_data[column] = pd.to_numeric(multiple_data[column], errors="coerce")

multiple_data = multiple_data.dropna()
print("Dataset shape:", multiple_data.shape)
display(multiple_data.head())

"""Correlation matrix and significance testing"""

correlation_matrix = multiple_data.corr()
display(correlation_matrix)

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, fmt=".3f", cmap="coolwarm", center=0)
plt.title("Correlation Matrix — Multiple Linear Regression")
plt.show()

correlation_results = []
columns = multiple_data.columns

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):
        var1 = columns[i]
        var2 = columns[j]
        pair_data = multiple_data[[var1, var2]].dropna()
        r, p_value = stats.pearsonr(pair_data[var1], pair_data[var2])

        print(f"\n{var1} vs. {var2}")
        print("H0: ρ = 0 | H1: ρ ≠ 0")
        print(f"Correlation (r) = {r:.4f}, p-value = {p_value:.6f}")

        if p_value < ALPHA:
            print(f"Result: Significant at alpha={ALPHA}")
        else:
            print("Result: Not statistically significant")

        correlation_results.append({
            "Variable 1": var1,
            "Variable 2": var2,
            "Correlation (r)": r,
            "p-value": p_value,
            "Significant": "Yes" if p_value < ALPHA else "No"
        })

correlation_significance = pd.DataFrame(correlation_results)
display(correlation_significance)

"""Scatter plots"""

fig, axes = plt.subplots(1, len(numeric_columns)-1, figsize=(14, 5))

for number in range(len(numeric_columns)-1):

  axes[number].scatter(multiple_data[numeric_columns[number]], multiple_data[numeric_columns[-1]], alpha=0.5)
  axes[number].set_xlabel(f"{numeric_columns[number]}")
  axes[number].set_ylabel(f"{numeric_columns[-1]}")
  axes[number].set_title(f"{numeric_columns[number]} vs. {numeric_columns[-1]}")

plt.tight_layout()
plt.show()

"""Train-test split and model fitting"""

X = multiple_data[numeric_columns[:-1]]
y = multiple_data[numeric_columns[-1]]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE
)

multiple_model = LinearRegression()
multiple_model.fit(X_train, y_train)

intercept_multiple = multiple_model.intercept_
b_age = multiple_model.coef_[0]
b_login = multiple_model.coef_[1]

print("Multiple Linear Regression Model Coefficients:")
print(f"Intercept = {intercept_multiple:.6f}")
print(f"Age coefficient = {b_age:.6f}")
print(f"Last Login Days coefficient = {b_login:.6f}")
print(f"Equation: watch_hours = {intercept_multiple:.4f} + ({b_age:.6f} × age) + ({b_login:.6f} × last_login_days)")

X_ols_multiple_const = sm.add_constant(X_train)
ols_multiple_model = sm.OLS(y_train, X_ols_multiple_const).fit()
print(ols_multiple_model.summary())

"""Testing for significance (t-tests)"""

print("t-tests for individual regression coefficients")

for col in numeric_columns[:-1]:
    t_stat = ols_multiple_model.tvalues[col]
    p_val = ols_multiple_model.pvalues[col]
    print(f"\nVariable: {col}")
    print(f"t-statistic = {t_stat:.4f}")
    print(f"p-value = {p_val:.6f}")
    if p_val < ALPHA:
        print(f"Reject H0: {col} is a statistically significant predictor.")
    else:
        print(f"Do not reject H0: {col} is not a statistically significant predictor.")

"""Testing for significance (F-test)


"""

print("F-test for the overall regression model")
f_stat_multiple = ols_multiple_model.fvalue
f_p_value_multiple = ols_multiple_model.f_pvalue

print(f"F-statistic = {f_stat_multiple:.4f}")
print(f"p-value = {f_p_value_multiple:.6f}")
print(f"alpha = {ALPHA}")

if f_p_value_multiple < ALPHA:
    print(f"Reject H0: The overall regression model is statistically significant.")
else:
    print(f"Do not reject H0: The overall model is not statistically significant.")

"""Test set predictions"""

y_pred_multiple = multiple_model.predict(X_test)
multiple_predictions = X_test.copy()
multiple_predictions["Actual"] = y_test.values
multiple_predictions["Predicted"] = y_pred_multiple
multiple_predictions["Residual"] = multiple_predictions["Actual"] - multiple_predictions["Predicted"]

display(multiple_predictions.head(15))

"""Actual vs. predicted plot"""

plt.figure(figsize=(8, 6))
plt.scatter(multiple_predictions["Actual"], multiple_predictions["Predicted"], alpha=0.7)

min_val = min(multiple_predictions["Actual"].min(), multiple_predictions["Predicted"].min())
max_val = max(multiple_predictions["Actual"].max(), multiple_predictions["Predicted"].max())
plt.plot([min_val, max_val], [min_val, max_val], linestyle="--", color="red", label="Perfect prediction")

plt.xlabel("Actual Watch Hours")
plt.ylabel("Predicted Watch Hours")
plt.title("Actual vs. Predicted Values — Multiple Linear Regression")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

"""Predictive performance (model evaluation)"""

mae_multiple = mean_absolute_error(y_test, y_pred_multiple)
mse_multiple = mean_squared_error(y_test, y_pred_multiple)
rmse_multiple = np.sqrt(mse_multiple)
r_squared_multiple = r2_score(y_test, y_pred_multiple)
mape_multiple = calculate_mape(y_test, y_pred_multiple)

multiple_metrics = pd.DataFrame({
    "Metric": ["MAE", "MSE", "RMSE", "MAPE (%)", "R-squared"],
    "Value": [mae_multiple, mse_multiple, rmse_multiple, mape_multiple, r_squared_multiple]
})
display(multiple_metrics)

"""---------------------------------------------------------------

**Binary Logistic Regression**

Prepare the data and display summary statistics

```markdown
*Independent Variables (X) : watch_hours, last_login_days, number_of_profiles*

*Dependent Variable (Y) : churned (which would be predicted)*
```
"""

logistic_columns = [
    # "age",
    "watch_hours",
    "last_login_days",
    "number_of_profiles",
    "churned"
]

predictor_columns = [
    # "age",
    "watch_hours",
    "last_login_days",
    "number_of_profiles"
]

logistic_data = df[logistic_columns].copy()

for column in predictor_columns:
    logistic_data[column] = pd.to_numeric(logistic_data[column], errors="coerce")

logistic_data["churned"] = pd.to_numeric(logistic_data["churned"], errors="coerce")
logistic_data = logistic_data.dropna()

print("Dataset shape:", logistic_data.shape)
print("\nTarget variable (churned) distribution:")
print(logistic_data["churned"].value_counts())
display(logistic_data.head())

"""Display summary statistics


"""

print("Summary statistics for predictor variables:")
display(logistic_data[predictor_columns].describe())

print("Target variable proportions:")
target_counts = (
    logistic_data["churned"]
    .value_counts()
    .sort_index()
)

target_proportions = (
    logistic_data["churned"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
)


target_summary = pd.DataFrame({
    "Count": target_counts,
    "Percentage (%)": target_proportions
})
target_summary.index = ["Active (0)", "Churned (1)"]
display(target_summary)

"""Train-test split"""

X = logistic_data[predictor_columns]
y = logistic_data["churned"].astype(int)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
)

print("Training observations:", len(X_train))
print("Testing observations:", len(X_test))

print("\nTraining target proportions:")
print(y_train.value_counts(normalize=True))

print("\nTesting target proportions:")
print(y_test.value_counts(normalize=True))

"""Fit the logistic regression model"""

logistic_model = LogisticRegression(max_iter=2000, random_state=RANDOM_STATE)
logistic_model.fit(X_train, y_train)

y_prob = logistic_model.predict_proba(X_test)[:, 1]
classification_threshold = 0.50
y_pred = (y_prob >= classification_threshold).astype(int)

print("Logistic regression model fitted successfully.")
print(f"Classification threshold = {classification_threshold}")

"""Logistic regression equation"""

logistic_intercept = logistic_model.intercept_[0]
logistic_coefficients = logistic_model.coef_[0]

logistic_coefficients_table = pd.DataFrame({
    "Variable": predictor_columns,
    "Coefficient": logistic_coefficients,
    "Odds_Ratio": np.exp(logistic_coefficients)
})

display(logistic_coefficients_table)
print(f"Intercept = {logistic_intercept:.6f}")

print("\nLogistic regression equation (log-odds scale):")
equation = f"logit(p) = {logistic_intercept:.6f}"
for variable, coefficient in zip(predictor_columns, logistic_coefficients):
    sign = "+" if coefficient >= 0 else "-"
    equation += f" {sign} {abs(coefficient):.6f} × {variable}"
print(equation)

"""Predicted probabilities"""

logistic_predictions = X_test.copy()
logistic_predictions["Actual_Churn"] = y_test.values
logistic_predictions["Predicted_Probability_Churn"] = y_prob
logistic_predictions["Predicted_Churn_Decision"] = y_pred
logistic_predictions["Predicted_Label"] = logistic_predictions["Predicted_Churn_Decision"].map({0: "Active", 1: "Churned"})

display(logistic_predictions.head(15))

"""Classification metrics"""

# Calculate classification metrics

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
auc = roc_auc_score(y_test, y_prob)

classification_metrics = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1-score",
        "ROC-AUC"
    ],
    "Value": [
        accuracy,
        precision,
        recall,
        f1,
        auc
    ]
})

display(classification_metrics)

"""Confusion matrix"""

cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
print("Confusion matrix:")
print(cm)

plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["Active (0)", "Churned (1)"], yticklabels=["Active (0)", "Churned (1)"])
plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")
plt.title("Confusion Matrix — Binary Logistic Regression (Churn)")
plt.show()

"""Classification report"""

print("Classification report:")
print(classification_report(y_test, y_pred, target_names=["Active", "Churned"], zero_division=0))

"""ROC curve and AUC"""

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = roc_auc_score(y_test, y_prob)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, linewidth=2, label=f"Logistic Regression (AUC = {roc_auc:.4f})")
plt.plot([0, 1], [0, 1], linestyle="--", linewidth=1.5, label="Random classifier")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve — Binary Logistic Regression (Churn)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

print(f"ROC-AUC = {roc_auc:.4f}")

"""User-defined prediction"""

# Predict churn for a hypothetical Netflix subscriber
new_subscriber = pd.DataFrame({
    # "age": [35],
    "watch_hours": [30.0],
    "last_login_days": [100],
    "number_of_profiles": [5]
})

probabilities = logistic_model.predict_proba(new_subscriber)[0]
prob_active = probabilities[0]
prob_churn = probabilities[1]

prediction_binary = logistic_model.predict(new_subscriber)[0]
prediction = "Churned" if prediction_binary == 1 else "Active"

print("\n" + "=" * 50)
print("LOGISTIC REGRESSION CHURN PREDICTION")
print("=" * 50)

print("\nInput subscriber details:")
display(new_subscriber)

print(f"\nProbability of remaining Active: {prob_active:.4f} ({prob_active * 100:.2f}%)")
print(f"Probability of Churning:         {prob_churn:.4f} ({prob_churn * 100:.2f}%)")
print(f"\nPredicted Subscriber State:      {prediction}")

"""#TASK 4
**Supervised machine learning with decision trees**

Define Constants
"""

RANDOM_STATE = 42
TEST_SIZE = 0.20

"""Data Preparation"""

#useless for the model
columns_to_drop = [
    "churned",
    "customer_id",
    "log_watch_hours",
    "subscription_type_encoded"
]

#errors="ignore" makes the code safe even if a column is already missing
X = df.drop(columns=columns_to_drop, errors="ignore")
y = df["churned"]

# Convert categorical features to numbers (One-Hot Encoding)
X_encoded = pd.get_dummies(X, dtype=int)

print("Data prepared for Decision Tree modeling.")
print(f"Shape of features after encoding: {X_encoded.shape}")
print(f"Shape of target variable:         {y.shape}")

print(f"\nFeatures used ({X_encoded.shape[1]} total):")
print(X_encoded.columns.tolist())
print(f"\nTarget distribution (churned):")
print(y.value_counts())
print(f"\nClass balance (%):")
print((y.value_counts(normalize=True) * 100).round(2))

"""Train-Test Split"""

x_train, x_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
)
print(f"Training instances: {len(x_train)}")
print(f"Testing instances: {len(x_test)}")

#target proportion check to confirm stratification worked
print(f"\nTraining target proportions:")
print(y_train.value_counts(normalize=True).round(4))
print(f"\nTesting target proportions:")
print(y_test.value_counts(normalize=True).round(4))

"""Base Decision Tree Classifier"""

# Initialize and fit Decision Tree Classifier
classifier = DecisionTreeClassifier(random_state=RANDOM_STATE, max_depth=None, min_samples_leaf=1)
classifier.fit(x_train, y_train)

# Evaluation on test set
y_pred = classifier.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy of the baseline Decision Tree classifier: {accuracy * 100:.2f}%')

#tree structure info to highlight overfitting.
print(f"\nTree depth:        {classifier.get_depth()}")
print(f"Number of leaves:  {classifier.get_n_leaves()}")

"""Analysis of Tree Depths"""

depths = list(range(2, 21))
depth_results = []

for depth in depths:
    dt = DecisionTreeClassifier(max_depth=depth, random_state=RANDOM_STATE)
    dt.fit(x_train, y_train)

    train_pred = dt.predict(x_train)
    test_pred = dt.predict(x_test)

    depth_results.append({
        "Max Depth": depth,
        "Train Accuracy": accuracy_score(y_train, train_pred),
        "Test Accuracy": accuracy_score(y_test, test_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_test, test_pred),
        "Macro F1": f1_score(y_test, test_pred, average='macro', zero_division=0)
    })

depth_df = pd.DataFrame(depth_results)
display(depth_df.round(4))

# Plotting accuracy curves
plt.figure(figsize=(12, 6))
plt.plot(depth_df["Max Depth"], depth_df["Train Accuracy"],
         label="Train Accuracy", marker='o', color="steelblue")
plt.plot(depth_df["Max Depth"], depth_df["Test Accuracy"],
         label="Test Accuracy", marker='s', color="darkorange")
# CHANGE: added Balanced Accuracy line.
plt.plot(depth_df["Max Depth"], depth_df["Balanced Accuracy"],
         label="Balanced Accuracy (test)", marker='^', color="green", linestyle="--")
plt.title("Decision Tree: Accuracy vs. Max Depth")
plt.xlabel("Max Depth")
plt.ylabel("Score")
plt.xticks(depths)
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()

"""Analysis of Minimum Samples per Leaf

"""

min_samples_list = [1, 2, 5, 10, 15, 20, 30, 50, 100]
leaf_results = []

for msl in min_samples_list:
    dt = DecisionTreeClassifier(min_samples_leaf=msl, random_state=RANDOM_STATE)
    dt.fit(x_train, y_train)

    train_pred = dt.predict(x_train)
    test_pred = dt.predict(x_test)

    leaf_results.append({
        "Min Samples Leaf": msl,
        "Train Accuracy": accuracy_score(y_train, train_pred),
        "Test Accuracy": accuracy_score(y_test, test_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_test, test_pred),
        "Macro F1": f1_score(y_test, test_pred, average='macro', zero_division=0)
    })

leaf_df = pd.DataFrame(leaf_results)
display(leaf_df.round(4))

# Plotting accuracy curves
plt.figure(figsize=(12, 6))
plt.plot(leaf_df["Min Samples Leaf"], leaf_df["Train Accuracy"],
         label="Train Accuracy", marker='o', color="steelblue")
plt.plot(leaf_df["Min Samples Leaf"], leaf_df["Test Accuracy"],
         label="Test Accuracy", marker='s', color="darkorange")
plt.plot(leaf_df["Min Samples Leaf"], leaf_df["Balanced Accuracy"],
         label="Balanced Accuracy (test)", marker='^', color="green", linestyle="--")
plt.title("Decision Tree: Accuracy vs. Min Samples per Leaf")
plt.xlabel("Min Samples Leaf")
plt.ylabel("Score")
plt.grid(True, alpha=0.3)
plt.legend()
plt.tight_layout()
plt.show()

"""Decision Tree vs. Decision Rule Classifier"""

def evaluate_cross_validation(clf, X_data, y_data, cv_splits=10):
    skf = StratifiedKFold(n_splits=cv_splits, shuffle=True, random_state=RANDOM_STATE)

    acc_scores, bal_acc_scores, prec_scores, rec_scores, f1_scores, gmean_scores = [], [], [], [], [], []

    for train_index, test_index in skf.split(X_data, y_data):
        X_tr, X_te = X_data.iloc[train_index], X_data.iloc[test_index]
        y_tr, y_te = y_data.iloc[train_index], y_data.iloc[test_index]

        clf.fit(X_tr, y_tr)
        y_pred = clf.predict(X_te)

        acc_scores.append(accuracy_score(y_te, y_pred))
        bal_acc_scores.append(balanced_accuracy_score(y_te, y_pred))
        prec_scores.append(precision_score(y_te, y_pred, average='macro', zero_division=0))
        rec_scores.append(recall_score(y_te, y_pred, average='macro', zero_division=0))
        f1_scores.append(f1_score(y_te, y_pred, average='macro', zero_division=0))
        gmean_scores.append(geometric_mean_score(y_te, y_pred, average='macro'))

    results = pd.DataFrame({
        "Accuracy": acc_scores,
        "Balanced Accuracy": bal_acc_scores,
        "Precision": prec_scores,
        "Recall": rec_scores,
        "F1 Score": f1_scores,
        "G-Mean": gmean_scores
    })
    results.index = [f"Fold {i+1}" for i in range(cv_splits)]
    results.loc["Average"] = results.mean(numeric_only=True)
    return results


# 1. Decision Tree Evaluation
# min_samples_leaf - 5 (based on tuning above).
dt_model = DecisionTreeClassifier(max_depth=10, min_samples_leaf=5, random_state=RANDOM_STATE)
dt_results = evaluate_cross_validation(dt_model, X_encoded, y)
print("=== Complex Decision Tree (max_depth=10, min_samples_leaf=5) ===")
print("=== Stratified 10-Fold Cross-Validation Results ===")
display(dt_results.round(4))

# 2. Rule-Based Classifier Evaluation
rule_model = DecisionTreeClassifier(max_depth=3, random_state=RANDOM_STATE)
rule_results = evaluate_cross_validation(rule_model, X_encoded, y)
print("\n=== Rule-Based Decision Tree (max_depth=3) ===")
print("=== Stratified 10-Fold Cross-Validation Results ===")
display(rule_results.round(4))

"""Extracted IF-THEN Rules from the Rule-Based Classifier"""

from sklearn.tree import plot_tree

rule_model.fit(X_encoded, y)
rules = export_text(rule_model, feature_names=list(X_encoded.columns))
print("Extracted Decision Rules (max_depth=3)")
print(" ")
print(rules)

plt.figure(figsize=(15, 5))

plot_tree(
    rule_model,
    feature_names=list(X_encoded.columns),
    class_names=["Active", "Churned"],
    filled=True,
    rounded=True,
    fontsize=11,
    impurity=True,
    proportion=False
)

plt.title("Decision Tree — Rule-Based Classifier (max_depth = 3)", fontsize=14)
plt.tight_layout()
plt.show()

"""#TASK 5

Unsupervised learning

Data Selection
"""

# COPY of the ORIGINAL dataset here ('df_netflix'), because the main 'df'
#has 'customer_id' removed.

try:
    df_netflix = pd.read_csv("netflix_customer_churn.csv")
    print("Original dataset loaded successfully for clustering.")
    print(f"Shape: {df_netflix.shape}")
except FileNotFoundError:
    raise FileNotFoundError(
        "The file 'netflix_customer_churn.csv' was not found. "
        "Please upload the original dataset to the Colab environment."
    )

# Select numerical variables for clustering
clustering_features = [
    "age",
    "watch_hours",
    "last_login_days"
]

# Clean from missing values
data_for_clustering = df_netflix[clustering_features].copy().dropna()

# align df_netflix with the cleaned data so indices match.
# This is crucial: kmedoids.medoid_indices_ returns indices into the cleaned data.
df_netflix = df_netflix.loc[data_for_clustering.index].reset_index(drop=True)
data_for_clustering = data_for_clustering.reset_index(drop=True)

print("\nNumber of observations to cluster:", len(data_for_clustering))
print(data_for_clustering.head())

# Create feature matrix
X_clustering = data_for_clustering[clustering_features].copy()

# Standardize variables
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_clustering)

print("\nMean after standardization (should be close to 0):\n", X_scaled.mean(axis=0).round(4))
print("\nStandard deviation after standardization (should be 1):\n", X_scaled.std(axis=0))

"""**K-Means**

INIT K-Means
"""

inertias = []
silhouette_scores = []

K_values = range(2, 11)


for k in K_values:

    # Create and fit the K-means model
    kmeans = KMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        n_init=20
    )

    labels = kmeans.fit_predict(X_scaled)

    # Store the within-cluster sum of squares
    inertias.append(kmeans.inertia_)

    # Store the silhouette score
    silhouette_scores.append(
        silhouette_score(X_scaled, labels)
    )

diagnostics_df = pd.DataFrame({
    "K": list(K_values),
    "Inertia": inertias,
    "Silhouette Score": silhouette_scores
})
print("K-Means diagnostics:")
display(diagnostics_df.round(4))

"""Elbow-plot"""

plt.figure(figsize=(10, 5))

plt.plot(K_values, inertias, marker="o", color="blue")

plt.xlabel("Number of clusters (K)")
plt.ylabel("Inertia")
plt.title("K-Means: Elbow Method")
plt.xticks(list(K_values))
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""Silhoutte score"""

plt.figure(figsize=(10, 5))

plt.plot(K_values, silhouette_scores, marker="o", color="green")

plt.xlabel("Number of clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("K-Means: Silhouette Score")
plt.xticks(list(K_values))
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Interpretation of silhouette scores:
# close to  1 -> well-separated clusters
# around    0 -> overlapping clusters
# negative    -> observations may be assigned to the wrong clusters

"""Fit the final K-Means model"""

# Fit final K-Means model with K=3 on Netflix data
K_FINAL = 5

kmeans = KMeans(
    n_clusters=K_FINAL,
    random_state=RANDOM_STATE,
    n_init=20
)

# Assign cluster labels to the Netflix DataFrame
df_netflix["kmeans_cluster"] = kmeans.fit_predict(X_scaled)
print(f"K-Means cluster label counts (K={K_FINAL}):")
print(df_netflix["kmeans_cluster"].value_counts().sort_index())

"""Visualize the clusters"""

# Visualize K-Means clusters for Netflix Users (Age vs Watch Hours)
plt.figure(figsize=(10, 7))

scatter = plt.scatter(
    df_netflix["watch_hours"],
    df_netflix["age"],
    c=df_netflix["kmeans_cluster"],
    cmap="viridis",
    s=30,
    alpha=0.6,
    edgecolor="k",
    linewidth=0.2
)

centroids_original = scaler.inverse_transform(kmeans.cluster_centers_)
plt.scatter(
    centroids_original[:, 1],  # watch_hours
    centroids_original[:, 0],  # age
    c="red",
    s=250,
    marker=".",
    linewidth=1.5,
    label="Centroids"
)

plt.xlabel("Watch Hours")
plt.ylabel("Age")
plt.title(f"K-Means Clustering (K={K_FINAL}) — Age vs. Watch Hours")
plt.grid(True, alpha=0.3)

plt.legend(
    handles=scatter.legend_elements()[0] + [
        plt.Line2D([], [], marker='.', color='red', linestyle='None',
                   markersize=12, label='Centroids')
    ],
    labels=[f"Cluster {i}" for i in range(K_FINAL)] + ["Centroids"]
)

plt.tight_layout()
plt.show()

"""Examine the cluster centers"""

centers_original = scaler.inverse_transform(kmeans.cluster_centers_)

centers_df = pd.DataFrame(
    centers_original,
    columns=clustering_features
)
centers_df.index.name = "Cluster"

print("K-Means Cluster Centroids (typical customer profiles):")
display(centers_df.round(2))

"""-------------------------------------------------------

**K-Medoid**

Fit K-Medoids
"""

kmedoids = KMedoids(
    n_clusters=K_FINAL,
    random_state=RANDOM_STATE,
    metric="euclidean"
)

df_netflix["kmedoids_cluster"] = kmedoids.fit_predict(X_scaled)
print(f"K-Medoids cluster label counts (K={K_FINAL}):")
print(df_netflix["kmedoids_cluster"].value_counts().sort_index())

"""Visualize the clusters"""

# Visualize K-Medoids clusters
plt.figure(figsize=(10, 7))

scatter = plt.scatter(
    df_netflix["watch_hours"],
    df_netflix["age"],
    c=df_netflix["kmedoids_cluster"],
    cmap="viridis",
    s=30,
    alpha=0.6,
    edgecolor="k",
    linewidth=0.2
)

medoid_indices = kmedoids.medoid_indices_
medoids_original = data_for_clustering.iloc[medoid_indices]

plt.scatter(
    medoids_original["watch_hours"],
    medoids_original["age"],
    c="red",
    s=250,
    marker=".",
    linewidth=1.5,
    label="Medoids"
)

plt.xlabel("Watch Hours")
plt.ylabel("Age")
plt.title(f"K-Medoids Clustering (K={K_FINAL}) — Age vs. Watch Hours")
plt.grid(True, alpha=0.3)

plt.legend(
    handles=scatter.legend_elements()[0] + [
        plt.Line2D([], [], marker='.', color='red', linestyle='None',
                   markersize=12, label='Medoids')
    ],
    labels=[f"Cluster {i}" for i in range(K_FINAL)] + ["Medoids"]
)

plt.tight_layout()
plt.show()

"""Identify selected variables as medoids"""

# Identify actual user profiles acting as medoids
medoid_indices = kmedoids.medoid_indices_

medoid_df = df_netflix.iloc[medoid_indices][
    ["customer_id"] + clustering_features + ["kmedoids_cluster"]
].copy()

medoid_df = medoid_df.rename(columns={"kmedoids_cluster": "assigned_cluster"})
medoid_df = medoid_df.set_index("assigned_cluster").sort_index()

print("Representative real customers (medoids) chosen from the database:")
display(medoid_df)

"""**Compare the results**

Select comparison data
"""

# Create cluster comparison dataframe for first 20 records (K-Means vs K-Medoids only)
comparison = df_netflix[
    [
        "customer_id",
        "kmeans_cluster",
        "kmedoids_cluster"
    ]
].copy()

display(comparison.head(20))

"""Count observations in each cluster"""

# Display observations per cluster across models
print("Cluster sizes for Netflix customer database:")

sizes_df = pd.DataFrame({
    "K-Means": df_netflix["kmeans_cluster"].value_counts().sort_index(),
    "K-Medoids": df_netflix["kmedoids_cluster"].value_counts().sort_index()
})
sizes_df.index.name = "Cluster"
display(sizes_df)

"""Silhouette scores"""

# Calculate silhouette scores for K-means and K-medoids

methods = {
     "K-means": df_netflix["kmeans_cluster"],
    "K-medoids": df_netflix["kmedoids_cluster"]
}
print("Silhouette scores comparison:\n")
for name, labels in methods.items():

    score = silhouette_score(
        X_scaled,
        labels
    )

    print(f"{name}: {score:.3f}")